#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Params-Util
Version  : 1.102
Release  : 48
URL      : https://cpan.metacpan.org/authors/id/R/RE/REHSACK/Params-Util-1.102.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RE/REHSACK/Params-Util-1.102.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libi/libio-handle-util-perl/libio-handle-util-perl_0.01-2.debian.tar.xz
Summary  : 'Simple, compact and correct param-checking functions'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Params-Util-license = %{version}-%{release}
Requires: perl-Params-Util-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
# NAME
Params::Util - Simple, compact and correct param-checking functions
# SYNOPSIS

%package dev
Summary: dev components for the perl-Params-Util package.
Group: Development
Provides: perl-Params-Util-devel = %{version}-%{release}
Requires: perl-Params-Util = %{version}-%{release}

%description dev
dev components for the perl-Params-Util package.


%package license
Summary: license components for the perl-Params-Util package.
Group: Default

%description license
license components for the perl-Params-Util package.


%package perl
Summary: perl components for the perl-Params-Util package.
Group: Default
Requires: perl-Params-Util = %{version}-%{release}

%description perl
perl components for the perl-Params-Util package.


%prep
%setup -q -n Params-Util-1.102
cd %{_builddir}
tar xf %{_sourcedir}/libio-handle-util-perl_0.01-2.debian.tar.xz
cd %{_builddir}/Params-Util-1.102
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Params-Util-1.102/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Params-Util
cp %{_builddir}/Params-Util-1.102/LICENSE %{buildroot}/usr/share/package-licenses/perl-Params-Util/27a14e34d2e75b1794c713418c26874bfc78d4c5
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-Params-Util/c7cbead4fc445ef2748335e1d1a81a21d992aad2
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Params::Util.3
/usr/share/man/man3/Params::Util::PP.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Params-Util/27a14e34d2e75b1794c713418c26874bfc78d4c5
/usr/share/package-licenses/perl-Params-Util/c7cbead4fc445ef2748335e1d1a81a21d992aad2

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
